### ISSUE TITLE
ValueError: non-hexadecimal number found in fromhex() arg at position 0

### ISSUE THREAD

**Issue by suitable4kids** [admin-ping/-SharpWxDump-decode.py#1]
Traceback (most recent call last):
  File "A:/-SharpWxDump-decode.py-main/wx_decode.py", line 86, in <module>
    Decode(i)
  File "A:/-SharpWxDump-decode.py-main/wx_decode.py", line 51, in Decode
    password = bytes.fromhex(input_pass.replace(' ', ''))
ValueError: non-hexadecimal number found in fromhex() arg at position 0
脚本运行出错，求教

**Comment by suitable4kids** [comment]
发现问题了，当前版本不受支持： 3.9.5.81
